import 'package:get/get.dart';

class AppTranslations implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          'hey_you': 'أهلاً بك',
          'create_an_account_and_access': 'إنشاء حساب والوصول إلى آلاف من المواد الرائعة\n                        للتمتع بمزايا التطبيق',
          'start_now': 'ابدأ الآن',
          'dont_have_account': 'هل لديك حساب؟',
          'create_account': 'إنشاء حساب',
          'welcome_to_tawafuq_application': 'أهلا بك في تطبيق توافق!',
          'welcome_to_application': 'الرجاء اختيار نوع الحساب للاستمرار',
          'register_new_pair': 'تسجيل زوج جديد!',
          'oh_grant_good_wife': 'اللهم ارزقنى الزوجة الصالحة',
          'user_name': 'اسم المستخدم',
          'username_nickname_that': 'اسم المستخدم هو اسمك المستعار الذى يظهر لجميع \nالأعضاء. لذا يجب أن يكون لائق ومحترم ويجب أن لا يزيد \nعن 15 حرف.',
          'next': 'التالي',
          'enter_username': 'أدخل اسم المستخدم.....',
          'to_continue_not_log': 'للمتابعة قم بتسجيل الدخول',
          'welcome_to_the_application': 'مرحبًا بك في تطبيق توافق!',
          'password': 'كلمة المرور',
          'please_confirm_your_password_here': 'يرجى تأكيد كلمة المرور هنا',
          'forget_password': 'نسيت كلمة المرور ؟',
          'sing_up': 'تسجيل الدخول',
          'don_have_account': 'ليس لديك حساب؟ ',
          'please_click_password': 'يرجى إدخال كلمة المرور هنا ',
          'please_click_the_password': 'تأكيد كلمة المرور',
          'figures_special_characters': 'يجب ألا يقل طولها عن 6 أحرف وألا تحتوي على\n علامات أو أشكال أو حروف خاصة.',
          'nationality': 'الجنسيه',
          'saudi': 'سعودي',
          'country': 'الدولة',
          'city': 'المدينة',
          'account_status': 'حالة الحساب',
          'type_marriage': 'نوع الزواج',
          'age': 'العمر:',
          'children': 'الأطفال',
          'kg': 'الموزن (كغم)',
          'length': 'الطول (سم)',
          'skin': 'لون البشرة',
          'physique': 'بنية الجسم',
          'choose_weight': 'أدخل وزنك',
          'choose_height': 'أدخل طولك',
          'choose_tone': 'اختر لون البشرة',
          'choose_structure': 'اختر بنية الجسم',
          'religious_commitment': 'الإلتزام الديني',
          'choose_religious_commitment': 'اختر إلتزامك الديني',
          'prayer': 'الصلاة',
          'choose_prayer_range': 'اختر مدى صلاتك',
          'smoking': 'التدخين',
          'smoking_': 'مدخن',
          'non_smoking': 'غير مدخن',
          'choose_whether_smoke_not': 'اختر هل أنت مدخن ام لا',
          'beard': 'اللحية',
          'beard_': 'ملتحي',
          'non_beard': 'غير ملتحي',
          'choose_whether_bearded_not': 'اختر هل أنت ملتحى ام لا',
          'educational_qualification': 'المؤهل التعليمي',
          'choose_educational_qualification': 'المؤهل التعليمي',
          'financial_status': 'الوضع المادي',
          'choose_physical_mode': 'اختر الوضع المادي',
          'education_field': 'مجال التعليم',
          'choose_field_work': 'اختر مجال العمل',
          'function': 'الوظيفة',
          'enter_job_here': 'أدخل الوظيفة هنا',
          'choose_your_educational': 'اختر إلمؤهل التعليمي',
          'characteristics_relationship_with': 'مواصفات شريكة حياتك التى ترغب الارتباط بها',
          'write_specifications_here': 'اكتب المواصفات هنا...',
          'please_write_erious_manner': 'يرجى الكتابة بطريقة جادة. يمنع في هذا القِسم كتابة\n بريدك الإلكتروني أوو رقم هاتفك.',
          'write_specifications_here': 'اكتب المواصفات هنا...',
          'self': 'تحدث عن نفسك',
          'self_here': 'تحدث عن نفسك هنا',
          'enter_self': 'تحدث عن نفسك',
          'please_write': 'يرجى الكتابة بطريقة جادة. يمنع في هذا \nالقِسم كتابة بريدك الإلكتروني أوو رقم هاتفك.',
          'full_name': 'الإسم الكامل',
          'phone': 'رقم الهاتف',
          'email': 'الربريد الالكتروني:',
          'enter_full_name': 'أدخل الاسم كاملا هنا',
          'enter_mobile': 'أدخل رقم الجوال هنا',
          'enter_email': 'أدخل البريد الالكتروني هنا',
          'conditions': 'شروط التطبيق',
          'clicking_create_account_agree': 'بضغطك على زر إنشاء حساب فإنك توافق على',
          'terms_and_conditions': ' شروط و',
          'terms_of_use': 'قوانين الإستخدام',
          'check_your_email': 'تحقق من بريدك الإلكتروني',
          'verification_email': 'أدخل بريدك الالكتروني في الأسفل حتى نرسل لك رمز \n                           التحقق الخاص بك.',
          'settings': 'الأعدادات',
          'profile': 'الملف الشخصي',
          'notifications': 'الاشعارات',
          'list_interests': 'قائمة الإهتمام',
          'ignore_list': 'قائمة التجاهل',
          'cares_about_me': 'من يهتم بي',
          'members_photo': 'صور الأعضاء',
          'success_stories': 'قصص النجاح',
          'compatibility_card': 'بطاقة توافق',
          'tawafuq_blog': 'مدونة توافق',
          'call_us': 'اتصل بنا',
          'share_app': 'مشاركة التطبيق',
          'confidentiality_policy': 'سياسة السرية',
          'about_us': 'نبذة عنا',
          'report_problem': 'إبلاغ عن مشكلة',
          'terms_conditions': 'الشروط والأحكام',
          'delete_account': 'حذف الحساب',
          'log_out': 'تسجيل خروج',
          'all_members': 'جميع الأعضاء',
          'name': 'الأسم:',
          'residency': 'الأقامه:',
          'notfiactions': 'الأشعارات',
          'latest_notifications': 'أخر الأشعارات',
          'member_rose': 'قام العضو',
          'visiting': 'بزياره',
          'personal_file': 'ملفك الشخصي',
          'days_ago': 'منذ 5 أيام',
          'tawafuq_local': 'في حالة قمت بشراء بطاقة توافق من الوكيل \nالمحلي ، فسيرسل لك رقم لتفعيل باقة التميز ، قم\n بإدخاله في الخانة أسفله وسيتم ترقية حسابك الى\n العضوية المميزة مباشرة',
          'card_number': 'رقم بطاقة التوافق',
          'enter_card': 'أدخل رقم البطاقة هنا',
          'activate_card': 'تفعيل البطاقه',
          'excellence_package': 'ماهي باقة التميز',
          'list_articles': 'قائمة المقالات',
          'articles': '6 مقالات',
          'more': 'المزيد......',
          'about_app': 'حول التطبيق',
          'vision': 'رؤيتنا',
          'mission': 'مهمتنا',
          'services': 'خدماتنا',
          'upon_client': 'عند موافقه العميل المبدئيه على التصميم يتم ازالة هذا النص \nمن التصميم ويتم وضع النصوص النهائية المطلوبة للتصميم ويقول \nالبعض ان وضع النصوص التجريبية بالتصميم قد تشغل المشاهد عن \nوضع الكثير من الملاحظات او الانتقادات للتصميم الاساسي',
          'do_any_questions': 'هل لديك أى استفسار؟ لا تترد وتواصل معنا وأخبرنا بكل ما \nهو  جديد',
          'enter_phone_number': 'أدخل رقم الهاتف',
          'number_characters': '(عدد الأحرف لا يزيد عن 200 حرف)',
          'leave_message': 'اكنب رسالتك هنا....',
          'problem': 'للإبلاغ عن مشكلة يرجى ملئ الحقول التالية وسيتم \nالتواصل مع الفريق المختص.',
          'message_text':'نص الرساله',
          'types_collect':'1. أنواع البيانات التي نجمعها',
          'personal_data':'2. استخدام بياناتك الشخصية',
          'disclosure_personal_data':'3. الإفصاح عن بياناتك الشخصية',
          'tawafuq_details':'تفاصيل المقاله',
          'home':'الرئيسية',
          'pakege':'باقة التميز',
          'members':'الأعضاء',
          'chats':'الدردشات',
          'search':'ابحث هنا....',
          'aya':'“وَلَكِنْ لا تُوَاعِدُوهُنَّ سِرًّا إِلَّاأَنْ تَقُولُوا قَوْلًا مَعْرُوفًا”',
          'intrections':'شكرا لك لإستخدام تطبيق توافق للزواج ننتقدم\n بخالص الشكر والامتنان لفريق التطبيق على\n جهودهم المستمرة في خلق فرص للقلوب \nالواعية لتجد طريقها لبعضها.',
          'app_evaluation':'تقييم التطبيق',
          'membership_number':'رقم العضوية:',
          'subscription_time':'وقت الاشتراك :',
          'check_email':'تحقق من البريد الإلكتروني',
          'send':'إرسال رسالة قصيرة',
          'advantages':'المزايا',
          'price':'الأسعار',
          'pyment':'طرق الدفع',
          'subscribe':'يمكنك الآن الاشتراك من خلال رصيد الجوال عبر وكيلن\nا المعتمد اتصل الآن على الرقم التالي أو إرسال \nرسالة نصية قصيرة.',
          'bundle_services':'مجمعة من الخدمات والخصائص المميزة تزيد',
          'increase':'من فعاليتك في التطبيق عبر عرض ملفك\n بشكل أفضل ونشره بشكل أوسع لتحقيق \nهدفك بشكل أسرع.',
          'boarding_title1':'اكتشف شريك حياتك',
          'subtitle1':'المثالي',
          'details1':'يُمكن للأفراد البحث عن شريك متوافق من\n خلال تصفح ملفات الآخرين واستخدام\n ميزات الفلترة والبحث المخصصة',
          'boarding_title2':'ابدأ رحلتك نحو ',
          'subtitle2':'الزواج',
          'details2':'تتيح للمستخدمين إنشاء ملف شخصي\n يحتوي على معلومات عنهم، مثل العمر،\n الهوايات، الخلفية الثقافية، في شريك الحياة',
          'boarding_title3':'أهلا بك مجددا في ',
          'subtitle3':' تطبيق توافق',
          'skip':' تخطى',
          'arabic':'العربيه',
          'details3':'تطبيق يهدف إلى تسهيل عملية البحث \nعن شريك الحياة وتوفير منصة آمنة للتواصل\n والتفاعل بين الأفراد الباحثين عن شريك\n للارتباط والزواج',
          'english':'الأنجليزيه',
          'successfully':'تم تسجيل الدخول لتطبيق توافق بنجاح',
          'submit_review':'أرسل التقييم',
          'all':'الكل',
          'le':'يجب عليك اختيار اللغة الجديدة\n لتكتمل استكمال تسجيل الدخول',
          'rating':'تقييمك يهمنا كثيرًا. نأمل \nأن تشاركنا تجربتك لتساعدنا في\n تحسين وتطوير التطبيق بشكل\n مستمر. شكرًا لوقتك \nومشاركتك',
          'females':'الإناث',
          'male':'الذكور',
          'members_online_now':'الأعضاء المتواجدين الآن',
          'residence':'الإقامة:',
          'online':'المتواجدون الآن:',
          'visited':'من زار بياناتي',
          'new_members':'أعضاء جدد',
          'distinguished_members':'الأعضاء المتمزين',
          'health_conditions':'الحالات الصحية',
          'automated_finder':'الباحث الآلي',
          'management':'إشعارات من الإدارة',
          'cares_about':'من يهتم بي',
          'ignore':'من أضافني لقائمة التجاهل',
          'deleted_ignore_list':'من حذفني من قائمة تجاهله',
          'select_country':'اختر الدولة',
          'select_nationality':'إختر الجنسية',
          'select_city':'إختر المدينة',
          'photo':'من أعطاني صلاحية بمشاهدة\n صورته',
          'success_story':'قصة نجاح',
          'god_together_goodness':'بَارَكَ اللَّهُ لَكَ، وبَارَكَ عَلَيْكَ، وجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
          'congratu_finding_half':'نهنئ جميع المشتركين الذين وفقهم الله بإيجاد نصفهم الآخر',
          'registration_period':'مدة التسجيل :',
          'message':'الرساله:',
          'save':'حفظ',
          'personal_information':'المعلومات الشخصية',
          'personal_information_file':'معلومات الملف الشخصي',
          'update_personal':'بإمكانك تحديث بياناتك الشخصية من خلال الحقول التالية',
          'profile_information_update':'تم تعديل معلومات الملف الشخصي بنجاح',
          'delete_not':'حذف الإشعارات',
          'delete_all_notifications':'هل تود فعلا حذف كل الإشعارات',
          'yes':'نعم',
          'no':'لا',
          'colse':'إلغاء ',
          'all_notifications_deleted':'تم  حذف جميع الإشعارات بنجاح',
          'receive':'للحصول على الخصم الخاص بك يرجى تسجيل\n الدخول للتطبيق',
          'appear':'ظاهر ',
          'disappear':'مخفي ',
          'select_account_status': 'حدد حالة الحساب',
          'select_marriage_type': 'حدد نوع الزواج',
          'enter_age': 'أدخل العمر',
          'enter_children': 'أدخل عدد الأطفال',
          'password_must_be_more_than_6': 'كلمة المرور يجب أن تكون أكثر من ستة أحرف',
          'tow_password_not_match': 'كلمتا المرور غير متطابقتان',
          'enter_description': 'أدخل الوصف',

        },
        "en": {
          'hey_you': 'Hey, you',
          'create_an_account_and_access': 'Create an account and access thousands of great stuff to enjoy                         \n the benefits of the app',
          'start_now': 'Start Now',
          'dont_have_account': 'do you have an account?',
          'create_account': 'Create Account',
          'welcome_to_tawafuq_application': 'Welcome to Tawanda application!',
          'welcome_to_application': 'الرجاء اختيار نوع الحساب للاستمرار',
          'register_new_pair': 'Register a new pair!',
          'oh_grant_good_wife': 'Oh God, grant me a good wife',
          'user_name': 'User Name',
          'username_nickname_that': 'Username is your nickname that appears to all \n members. Therefore, it must be decent and \n respectful and must not exceed \n 15 characters.',
          'next': 'Next',
          'enter_username': 'Enter User Name.......',
          'to_continue_not_log': 'To continue, log in',
          'welcome_to_the_application': 'Welcome to the Tawafuq application!',
          'password': 'password',
          'please_confirm_your_password_here': 'Please confirm your password here',
          'forget_password': 'Forget Password?',
          'sing_up': 'Sing Up',
          'don_have_account': 'Dont have an account?',
          'please_click_password': 'Please click on the password here',
          'please_click_the_password': 'Please click on the password here',
          'figures_special_characters': 'It must be at least 6 characters long \nand contain no signs, figures or special characters.',
          'nationality': 'Nationality',
          'saudi': 'Saudi',
          'country': 'Country',
          'city': 'City',
          'account_status': 'Account status',
          'type_marriage': 'Type of marriage',
          'age': 'Age:',
          'children': 'Children',
          'kg': 'Weight (kg)',
          'length': 'Length (cm)',
          'skin': 'Skin colour',
          'physique': 'Physique',
          'choose_weight': 'Enter weight',
          'choose_height': 'Enter your height',
          'choose_tone': 'Choose skin tone',
          'choose_structure': 'Choose body structure',
          'religious_commitment': 'Religious commitment',
          'choose_religious_commitment': 'Choose your religious commitment',
          'prayer': 'Prayer',
          'choose_prayer_range': 'Choose your prayer range',
          'smoking': 'Smoking',
          'smoking_': 'Smoking',
          'non_smoking': 'Non-Smoking',
          'choose_whether_smoke_not': 'Choose whether you smoke or not',
          'beard': 'Beard',
          'choose_whether_bearded_not': 'Choose whether you are bearded or not',
          'educational_qualification': 'Educational qualification',
          'choose_educational_qualification': 'Choose your educational qualification',
          'financial_status': 'Financial Status',
          'choose_physical_mode': 'Choose physical mode',
          'education_field': 'Education Field',
          'choose_field_work': 'Choose your field of work',
          'function': 'Function',
          'enter_job_here': 'Enter job here',
          'choose_your_educational': 'Choose your educational qualification',
          'characteristics_relationship_with': 'The characteristics of your life partner that you want to have a relationship with',
          'write_specifications_here': 'Write specifications here...',
          'please_write_erious_manner': 'Please write in a serious manner. In this section,\n it is prohibited to write your email or phone number.',
          'self': 'talk about your self',
          'self_here': 'Talk about yourself here',
          'please_write': 'Please write in a serious manner. In\n this section, it is prohibited to \n write your email or phone number.',
          'enter_self': 'Enter Self',
          'full_name': 'Full name',
          'phone': 'Phone',
          'email': 'Email:',
          'enter_full_name': 'Enter full name here',
          'enter_mobile': 'Enter mobile number here',
          'enter_email': 'Enter email here',
          'conditions': 'Application terms',
          'clicking_create_account_agree': 'By clicking on the Create Account button, you agree to',
          'terms_and_conditions': 'Terms and conditions',
          'terms_of_use': 'Terms of use',
          'check_your_email': 'Check your email',
          'verification_email': 'Enter your email below so we can send you \n                            your verification code.',
          'settings': 'Settings',
          'profile ': 'Profile',
          'notifications': 'Notifications',
          'list_interests': 'List of interests',
          'ignore_list': 'Ignore list',
          'cares_about_me': 'Who cares about me',
          'members_photo': 'Members photos',
          'success_stories': 'Success stories',
          'compatibility_card': 'Compatibility card',
          'tawafuq_blog': 'Tawafuq blog',
          'call_us': 'Call us',
          'share_app': 'Share the app',
          'confidentiality_policy': 'Confidentiality policy',
          'about_us': 'About us',
          'report_problem': 'Report a problem',
          'terms_conditions': 'Terms and Conditions',
          'delete_account': 'Delete account',
          'log_out': 'Log out',
          'all_members': 'All Members',
          'name': 'Name:',
          'residency': 'Residency:',
          'notfiactions': 'Notfiactions',
          'latest_notifications': 'Latest Notifications',
          'member_rose': 'The member rose',
          'visiting': 'Visiting',
          'personal_file': 'Personal File',
          'days_ago': '5 days ago',
          'tawafuq_local': 'If you purchase a Tawafuq card from the \nlocal agent, he will send you a number to\n activate the Distinction Package. Enter \nit in the box below and your account will\n be upgraded to the Distinguished \nMembership directly',
          'card_number': 'Compatibility card number',
          'enter_card': 'Enter the card number here',
          'activate_card': 'Activate the card',
          'excellence_package': 'What is the Excellence Package',
          'list_articles': 'List of articles',
          'articles': '6 articles',
          'more': 'more...',
          'about_app': 'About the app',
          'vision': 'Our vision',
          'mission': 'Our mission',
          'services': 'Services',
          'upon_client': 'Upon the clients initial approval of the design,\n this text is removed from the design and the final\n texts required for the design are placed. Some \nsay that placing experimental texts in the design\n may distract the viewer from making many \ncomments or criticisms of the basic design.',
          'do_any_questions': 'Do you have any questions? Do not hesitate and contact us and tell us \n everything new',
          'enter_phone_number': 'Enter a phone number',
          'number_characters': '(The number of characters does not exceed 200 characters)',
          'leave_message': 'Leave your message here..',
          'problem': 'To report a problem, please fill out the following fields and the\n relevant team will be contacted.',
          'message_text':'Message text',
          'types_collect':'1. Types of data we collect',
          'personal_data':'2. Use of your personal data',
          'disclosure_personal_data':'3. Disclosure of your personal data',
          'tawafuq_details':'Tawafuq Details',
          'pakege':'Package',
          'home':'Home',
          'members':'Members',
          'chats':'chats',
          'search':'search here......',
          'aya':'“But do not date them secretly unless you say a known word.”',
          'intrections':'Thank you for using the Tawafuq application for \nmarriage. We extend our sincere thanks and gratitude to the work\n team for their efforts in creating opportunities for conscious \nhearts to find their way together.',
          'app_evaluation':'App evaluation',
          'membership_number':'Membership Number:',
          'subscription_time':'Subscription time:',
          'check_email':'Check email',
          'send':'Send a short message',
          'advantages':'Advantages',
          'price':'Price',
          'pyment':'payment method',
          'subscribe':'You can subscribe using your mobile\n balance via our authorized agent. Call\n now on the following number or\n send an SMS.',
          'bundle_services':'A complex of services and distinctive features increases',
          'increase':'Increase your effectiveness in the\n application by displaying your file better \nand disseminating it more widely to\n achieve your goal faster.',
          'boarding_title1':'Discover your life partner',
          'subtitle1':'Ideal',
          'details1':'Individuals can search for a compatible\n partner by browsing others profiles and using \ncustom filtering and search features',
          'boarding_title2':'Start your journey towards',
          'subtitle2':'marriage',
          'details2':'It allows users to create a profile\n that contains information about themselves, \nsuch as age, hobbies, cultural background, \n and life partner',
          'boarding_title3':'Welcome back to',
          'subtitle3':'Tawafuq application',
          'details3':'An application that aims to facilitate \nthe process of searching for a life partner and\n provide a safe platform for communication and \ninteraction between individuals searching for \na partner for relationship and marriage',
          'skip':'Skip',
          'arabic':'Arabic',
          'english':'English',
          'submit_review':'Submit a review',
          'le':'You must choose the new language\n to complete the login',
          'successfully':'You have successfully logged in to the Tawafuq application',
          'rating':'Your rating matters a lot\n to us. We hope that you will \nshare your experience with us\n to help us continuously improve and \ndevelop the application. Thanks for\n your time and participation',
          'all':'All',
          'females':'Females',
          'male':'Male',
          'members_online_now':'Members online now',
          'residence':'Residence:',
          'online':'Online',
          'visited':'Visitedd Data',
          'new_members':'New members',
          'distinguished_members':'Distinguished members',
          'health_conditions':'Health conditions',
          'automated_finder':'Automated finder',
          'management':'Notifications management',
          'cares_about':'Cares About',
          'ignore':'Added Ignore List',
          'deleted_ignore_list':'Deleted Ignore List',
          'photo':'gave permission to view\n his photo',
          'select_country':'Select country',
          'select_nationality':'Select Nationality  ',
          'select_city':'Select city',
          'success_story':'Success Story',
          'congratu_finding_half':'We congratulate all the participants who have been\n                        blessed by God with finding their other half',
          'god_together_goodness':'May God bless you, and bless you, and bring\n                       you together in goodness.',
          'registration_period':'Registration period: ',
          'message':'Message:',
          'save':'Save',
          'personal_information':'Personal Information',
          'update_personal':'You can update your personal data through the following fields',
          'personal_information_file':'Personal Information File',
          'profile_information_update':'Profile information has been successfully modified',
          'delete_not':'Delete notifications',
          'delete_all_notifications':'Do you really want to delete all notifications',
          'yes':'Yes',
          'no':'No',
          'all_notifications_deleted':'All notifications have been successfully deleted',
          'receive':'To receive your discount please log \n in to the application',
          'colse':'Colse',
          'appear':'Appear ',
          'disappear':'Disappear',
          'select_account_status':'Select account status',
          'select_marriage_type': 'Select marriage type',
          'enter_age': 'Enter age',
          'enter_children': 'Enter children',
          'password_must_be_more_than_6': 'Password must be more than six characters',
          'tow_password_not_match': 'The two passwords do not match',
          'enter_description': 'Enter description',
        },
      };
}
